//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartyTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PartyTable()
        {
            this.BlacklistTables = new HashSet<BlacklistTable>();
            this.SongsForPartyTables = new HashSet<SongsForPartyTable>();
            this.UsersAtParties = new HashSet<UsersAtParty>();
        }
    
        public long ID { get; set; }
        public long ownerID { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public Nullable<double> locationLatitude { get; set; }
        public Nullable<double> locationLongitude { get; set; }
        public bool privacy { get; set; }
        public string Name { get; set; }
        public byte[] RowVersion { get; set; }
        public short AvailablePlaces { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BlacklistTable> BlacklistTables { get; set; }
        public virtual UserTable UserTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongsForPartyTable> SongsForPartyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAtParty> UsersAtParties { get; set; }
    }
}
