//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongRatingFromPartyTable
    {
        public long partyID { get; set; }
        public long userID { get; set; }
        public string songURL { get; set; }
        public int voteType { get; set; }
    
        public virtual SongsForPartyTable SongsForPartyTable { get; set; }
        public virtual UserTable UserTable { get; set; }
    }
}
