//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongsForPartyTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SongsForPartyTable()
        {
            this.SongRatingFromPartyTables = new HashSet<SongRatingFromPartyTable>();
        }
    
        public long partyID { get; set; }
        public string songURL { get; set; }
        public int rating { get; set; }
        public byte[] RowVersion { get; set; }
    
        public virtual PartyTable PartyTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongRatingFromPartyTable> SongRatingFromPartyTables { get; set; }
    }
}
