//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserTable()
        {
            this.PartyTables = new HashSet<PartyTable>();
            this.SongRatingFromPartyTables = new HashSet<SongRatingFromPartyTable>();
            this.UserLoginTables = new HashSet<UserLoginTable>();
            this.UsersAtParties = new HashSet<UsersAtParty>();
            this.FriendTables = new HashSet<FriendTable>();
            this.FriendTables1 = new HashSet<FriendTable>();
        }
    
        public long ID { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public bool accountType { get; set; }
        public int zip { get; set; }
        public Nullable<long> currentPartyID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartyTable> PartyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongRatingFromPartyTable> SongRatingFromPartyTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserLoginTable> UserLoginTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersAtParty> UsersAtParties { get; set; }
        public virtual ZIPTable ZIPTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendTable> FriendTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FriendTable> FriendTables1 { get; set; }
    }
}
