//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClientV2.WCFLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class UserTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.FriendTable[] FriendTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.FriendTable[] FriendTables1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.PartyTable[] PartyTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.SongRatingFromPartyTable[] SongRatingFromPartyTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserLoginTable[] UserLoginTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UsersAtParty[] UsersAtPartiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.ZIPTable ZIPTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool accountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> currentPartyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string firstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string lastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.FriendTable[] FriendTables {
            get {
                return this.FriendTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.FriendTablesField, value) != true)) {
                    this.FriendTablesField = value;
                    this.RaisePropertyChanged("FriendTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.FriendTable[] FriendTables1 {
            get {
                return this.FriendTables1Field;
            }
            set {
                if ((object.ReferenceEquals(this.FriendTables1Field, value) != true)) {
                    this.FriendTables1Field = value;
                    this.RaisePropertyChanged("FriendTables1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.PartyTable[] PartyTables {
            get {
                return this.PartyTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyTablesField, value) != true)) {
                    this.PartyTablesField = value;
                    this.RaisePropertyChanged("PartyTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.SongRatingFromPartyTable[] SongRatingFromPartyTables {
            get {
                return this.SongRatingFromPartyTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.SongRatingFromPartyTablesField, value) != true)) {
                    this.SongRatingFromPartyTablesField = value;
                    this.RaisePropertyChanged("SongRatingFromPartyTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserLoginTable[] UserLoginTables {
            get {
                return this.UserLoginTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserLoginTablesField, value) != true)) {
                    this.UserLoginTablesField = value;
                    this.RaisePropertyChanged("UserLoginTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UsersAtParty[] UsersAtParties {
            get {
                return this.UsersAtPartiesField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersAtPartiesField, value) != true)) {
                    this.UsersAtPartiesField = value;
                    this.RaisePropertyChanged("UsersAtParties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.ZIPTable ZIPTable {
            get {
                return this.ZIPTableField;
            }
            set {
                if ((object.ReferenceEquals(this.ZIPTableField, value) != true)) {
                    this.ZIPTableField = value;
                    this.RaisePropertyChanged("ZIPTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool accountType {
            get {
                return this.accountTypeField;
            }
            set {
                if ((this.accountTypeField.Equals(value) != true)) {
                    this.accountTypeField = value;
                    this.RaisePropertyChanged("accountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> currentPartyID {
            get {
                return this.currentPartyIDField;
            }
            set {
                if ((this.currentPartyIDField.Equals(value) != true)) {
                    this.currentPartyIDField = value;
                    this.RaisePropertyChanged("currentPartyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName {
            get {
                return this.firstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.firstNameField, value) != true)) {
                    this.firstNameField = value;
                    this.RaisePropertyChanged("firstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.lastNameField, value) != true)) {
                    this.lastNameField = value;
                    this.RaisePropertyChanged("lastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zip {
            get {
                return this.zipField;
            }
            set {
                if ((this.zipField.Equals(value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZIPTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class ZIPTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable[] UserTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int zipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable[] UserTables {
            get {
                return this.UserTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTablesField, value) != true)) {
                    this.UserTablesField = value;
                    this.RaisePropertyChanged("UserTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int zip {
            get {
                return this.zipField;
            }
            set {
                if ((this.zipField.Equals(value) != true)) {
                    this.zipField = value;
                    this.RaisePropertyChanged("zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FriendTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class FriendTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable UserTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable UserTable1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long idTwoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable UserTable1 {
            get {
                return this.UserTable1Field;
            }
            set {
                if ((object.ReferenceEquals(this.UserTable1Field, value) != true)) {
                    this.UserTable1Field = value;
                    this.RaisePropertyChanged("UserTable1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idOne {
            get {
                return this.idOneField;
            }
            set {
                if ((this.idOneField.Equals(value) != true)) {
                    this.idOneField = value;
                    this.RaisePropertyChanged("idOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long idTwo {
            get {
                return this.idTwoField;
            }
            set {
                if ((this.idTwoField.Equals(value) != true)) {
                    this.idTwoField = value;
                    this.RaisePropertyChanged("idTwo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PartyTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class PartyTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short AvailablePlacesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.BlacklistTable[] BlacklistTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.SongsForPartyTable[] SongsForPartyTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable UserTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UsersAtParty[] UsersAtPartiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime endDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> locationLatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> locationLongitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ownerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool privacyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime startDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short AvailablePlaces {
            get {
                return this.AvailablePlacesField;
            }
            set {
                if ((this.AvailablePlacesField.Equals(value) != true)) {
                    this.AvailablePlacesField = value;
                    this.RaisePropertyChanged("AvailablePlaces");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.BlacklistTable[] BlacklistTables {
            get {
                return this.BlacklistTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.BlacklistTablesField, value) != true)) {
                    this.BlacklistTablesField = value;
                    this.RaisePropertyChanged("BlacklistTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.SongsForPartyTable[] SongsForPartyTables {
            get {
                return this.SongsForPartyTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.SongsForPartyTablesField, value) != true)) {
                    this.SongsForPartyTablesField = value;
                    this.RaisePropertyChanged("SongsForPartyTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UsersAtParty[] UsersAtParties {
            get {
                return this.UsersAtPartiesField;
            }
            set {
                if ((object.ReferenceEquals(this.UsersAtPartiesField, value) != true)) {
                    this.UsersAtPartiesField = value;
                    this.RaisePropertyChanged("UsersAtParties");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime endDate {
            get {
                return this.endDateField;
            }
            set {
                if ((this.endDateField.Equals(value) != true)) {
                    this.endDateField = value;
                    this.RaisePropertyChanged("endDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> locationLatitude {
            get {
                return this.locationLatitudeField;
            }
            set {
                if ((this.locationLatitudeField.Equals(value) != true)) {
                    this.locationLatitudeField = value;
                    this.RaisePropertyChanged("locationLatitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> locationLongitude {
            get {
                return this.locationLongitudeField;
            }
            set {
                if ((this.locationLongitudeField.Equals(value) != true)) {
                    this.locationLongitudeField = value;
                    this.RaisePropertyChanged("locationLongitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ownerID {
            get {
                return this.ownerIDField;
            }
            set {
                if ((this.ownerIDField.Equals(value) != true)) {
                    this.ownerIDField = value;
                    this.RaisePropertyChanged("ownerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool privacy {
            get {
                return this.privacyField;
            }
            set {
                if ((this.privacyField.Equals(value) != true)) {
                    this.privacyField = value;
                    this.RaisePropertyChanged("privacy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime startDate {
            get {
                return this.startDateField;
            }
            set {
                if ((this.startDateField.Equals(value) != true)) {
                    this.startDateField = value;
                    this.RaisePropertyChanged("startDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongRatingFromPartyTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class SongRatingFromPartyTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.SongsForPartyTable SongsForPartyTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable UserTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long partyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string songURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int voteTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.SongsForPartyTable SongsForPartyTable {
            get {
                return this.SongsForPartyTableField;
            }
            set {
                if ((object.ReferenceEquals(this.SongsForPartyTableField, value) != true)) {
                    this.SongsForPartyTableField = value;
                    this.RaisePropertyChanged("SongsForPartyTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long partyID {
            get {
                return this.partyIDField;
            }
            set {
                if ((this.partyIDField.Equals(value) != true)) {
                    this.partyIDField = value;
                    this.RaisePropertyChanged("partyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string songURL {
            get {
                return this.songURLField;
            }
            set {
                if ((object.ReferenceEquals(this.songURLField, value) != true)) {
                    this.songURLField = value;
                    this.RaisePropertyChanged("songURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int voteType {
            get {
                return this.voteTypeField;
            }
            set {
                if ((this.voteTypeField.Equals(value) != true)) {
                    this.voteTypeField = value;
                    this.RaisePropertyChanged("voteType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class UserLoginTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable UserTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string emailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email {
            get {
                return this.emailField;
            }
            set {
                if ((object.ReferenceEquals(this.emailField, value) != true)) {
                    this.emailField = value;
                    this.RaisePropertyChanged("email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsersAtParty", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class UsersAtParty : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.PartyTable PartyTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.UserTable UserTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool adminPrivilegesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long partyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long userIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.PartyTable PartyTable {
            get {
                return this.PartyTableField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyTableField, value) != true)) {
                    this.PartyTableField = value;
                    this.RaisePropertyChanged("PartyTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.UserTable UserTable {
            get {
                return this.UserTableField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTableField, value) != true)) {
                    this.UserTableField = value;
                    this.RaisePropertyChanged("UserTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool adminPrivileges {
            get {
                return this.adminPrivilegesField;
            }
            set {
                if ((this.adminPrivilegesField.Equals(value) != true)) {
                    this.adminPrivilegesField = value;
                    this.RaisePropertyChanged("adminPrivileges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long partyID {
            get {
                return this.partyIDField;
            }
            set {
                if ((this.partyIDField.Equals(value) != true)) {
                    this.partyIDField = value;
                    this.RaisePropertyChanged("partyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short status {
            get {
                return this.statusField;
            }
            set {
                if ((this.statusField.Equals(value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long userID {
            get {
                return this.userIDField;
            }
            set {
                if ((this.userIDField.Equals(value) != true)) {
                    this.userIDField = value;
                    this.RaisePropertyChanged("userID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BlacklistTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class BlacklistTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.PartyTable PartyTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long partyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string songURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.PartyTable PartyTable {
            get {
                return this.PartyTableField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyTableField, value) != true)) {
                    this.PartyTableField = value;
                    this.RaisePropertyChanged("PartyTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long partyID {
            get {
                return this.partyIDField;
            }
            set {
                if ((this.partyIDField.Equals(value) != true)) {
                    this.partyIDField = value;
                    this.RaisePropertyChanged("partyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string songURL {
            get {
                return this.songURLField;
            }
            set {
                if ((object.ReferenceEquals(this.songURLField, value) != true)) {
                    this.songURLField = value;
                    this.RaisePropertyChanged("songURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SongsForPartyTable", Namespace="http://schemas.datacontract.org/2004/07/DataAccessLayer")]
    [System.SerializableAttribute()]
    public partial class SongsForPartyTable : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.PartyTable PartyTableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] RowVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebClientV2.WCFLogin.SongRatingFromPartyTable[] SongRatingFromPartyTablesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long partyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ratingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string songURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.PartyTable PartyTable {
            get {
                return this.PartyTableField;
            }
            set {
                if ((object.ReferenceEquals(this.PartyTableField, value) != true)) {
                    this.PartyTableField = value;
                    this.RaisePropertyChanged("PartyTable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] RowVersion {
            get {
                return this.RowVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.RowVersionField, value) != true)) {
                    this.RowVersionField = value;
                    this.RaisePropertyChanged("RowVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WebClientV2.WCFLogin.SongRatingFromPartyTable[] SongRatingFromPartyTables {
            get {
                return this.SongRatingFromPartyTablesField;
            }
            set {
                if ((object.ReferenceEquals(this.SongRatingFromPartyTablesField, value) != true)) {
                    this.SongRatingFromPartyTablesField = value;
                    this.RaisePropertyChanged("SongRatingFromPartyTables");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long partyID {
            get {
                return this.partyIDField;
            }
            set {
                if ((this.partyIDField.Equals(value) != true)) {
                    this.partyIDField = value;
                    this.RaisePropertyChanged("partyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string songURL {
            get {
                return this.songURLField;
            }
            set {
                if ((object.ReferenceEquals(this.songURLField, value) != true)) {
                    this.songURLField = value;
                    this.RaisePropertyChanged("songURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFLogin.ILogIn")]
    public interface ILogIn {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/CheckCredentials", ReplyAction="http://tempuri.org/ILogIn/CheckCredentialsResponse")]
        long CheckCredentials(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/CheckCredentials", ReplyAction="http://tempuri.org/ILogIn/CheckCredentialsResponse")]
        System.Threading.Tasks.Task<long> CheckCredentialsAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/RegisterUser", ReplyAction="http://tempuri.org/ILogIn/RegisterUserResponse")]
        long RegisterUser(WebClientV2.WCFLogin.UserTable user, WebClientV2.WCFLogin.UserLoginTable userLogin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILogIn/RegisterUser", ReplyAction="http://tempuri.org/ILogIn/RegisterUserResponse")]
        System.Threading.Tasks.Task<long> RegisterUserAsync(WebClientV2.WCFLogin.UserTable user, WebClientV2.WCFLogin.UserLoginTable userLogin);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILogInChannel : WebClientV2.WCFLogin.ILogIn, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogInClient : System.ServiceModel.ClientBase<WebClientV2.WCFLogin.ILogIn>, WebClientV2.WCFLogin.ILogIn {
        
        public LogInClient() {
        }
        
        public LogInClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogInClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogInClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogInClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public long CheckCredentials(string username, string password) {
            return base.Channel.CheckCredentials(username, password);
        }
        
        public System.Threading.Tasks.Task<long> CheckCredentialsAsync(string username, string password) {
            return base.Channel.CheckCredentialsAsync(username, password);
        }
        
        public long RegisterUser(WebClientV2.WCFLogin.UserTable user, WebClientV2.WCFLogin.UserLoginTable userLogin) {
            return base.Channel.RegisterUser(user, userLogin);
        }
        
        public System.Threading.Tasks.Task<long> RegisterUserAsync(WebClientV2.WCFLogin.UserTable user, WebClientV2.WCFLogin.UserLoginTable userLogin) {
            return base.Channel.RegisterUserAsync(user, userLogin);
        }
    }
}
